---
abstract: 'Bot::Cobalt plugin for looking up urban dictionary terms'
author:
  - 'Scott Miller <scott.j.miller@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bot-Cobalt-Plugin-Urban
requires:
  Bot::Cobalt: '0'
  Bot::Cobalt::Common: '0'
  HTTP::Tiny: '0'
  JSON: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/sjmiller/bot-cobalt-plugin-urban/issues
  repository: git://github.com/sjmiller/bot-cobalt-plugin-urban.git
version: '0.001'
